var MoviesJSON = [
    {
      "id": "1",
      "name":"!De Panzazo!",
      "filename":"!De Panzazo!.m4v",
      "artwork":"../img/artwork/00001/!De%20Panzazo!.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Carlos Loret de Mola, Denise Dresser, Elba Esther Gordillo",
      "main Genre":"Documentary",
      "genres":"Documentary",
      "release Date":"2012-02-24",
      "description":"¡De Panzazo! refleja la realidad de la educación en México y pone en evidencia que la sociedad mexicana pasa de panzazo en un sistema excluyente en el que no se logran aprendizajes para la vida. Vemos en esta película a mamás, papás, directores, maestros, funcionarios, representantes sindicales y líderes de opinión que trazan un cuadro global que no permite la indiferencia. Los datos, las entrevistas y lo que los propios alumnos filmaron con cámaras de mano dan pie a una indignación inteligente y también a darse cuenta de la parte que a cada uno le toca aportar. El proyecto se desarrolló por tres años entrando en la realidad de los alumnos y sus familias, captando la dinámica cotidiana de escuelas en lugares tan diversos del territorio nacional como Ciudad Juárez, el interior de Yucatán, Morelia, las sierras de Chiapas y Guerrero, así como Naucalpan e Iztapalapa en la zona metropolitana de la Ciudad de México.",
      "rating":"-- United States",
      "studio":"",
      "director":"Juan Carlos Rulfo, Carlos Loret de Mola",
      "producers":"",
      "screenwriters":"Carlos Loret de Mola, Mario Gutiérrez Vega",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/!De Panzazo!/!De Panzazo!.m4v"
    },
    {
      "id": "2",
      "name":"007: A View to a Kill",
      "filename":"007_ A View to a Kill.m4v",
      "artwork":"../img/artwork/00002/007_%20A%20View%20to%20a%20Kill.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Roger Moore, Christopher Walken, Tanya Roberts, Grace Jones, Patrick Macnee, Patrick Bauchau, David Yip, Fiona Fullerton, Willoughby Gray, Desmond Llewelyn, Lois Maxwell, Walter Gotell, Geoffrey Keen, Robert Brown",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1985-05-24",
      "description":"A newly developed microchip designed by Zorin Industries for the British Government that can survive the electromagnetic radiation caused by a nuclear explosion has landed in the hands of the KGB. James Bond must find out how and why. His suspicions soon lead him to big industry leader Max Zorin. The 14th film from the Legendary James Bond series starring Roger Moore as a British super agent.",
      "rating":"PG",
      "studio":"MGM, United Artists",
      "director":"John Glen",
      "producers":"Albert R. Broccoli, Tom Pevsner, Michael J. Wilson, Debbie McWilliams",
      "screenwriters":"Richard Maibaum, Michael J. Wilson",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ A View to a Kill/007_ A View to a Kill.m4v"
    },
    {
      "id": "3",
      "name":"007: Casino Royale",
      "filename":"007_ Casino Royale.m4v",
      "artwork":"../img/artwork/00003/007_%20Casino%20Royale.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Daniel Craig, Eva Green, Mads Mikkelsen, Jeffrey Wright, Giancarlo Giannini, Caterina Murino, Simon Abkarian, Isaach De Bankole, Jesper Christensen, Ivana Milicevic, Tobias Menzies, Claudio Santamaria, Sebastien Foucan, Malcolm Sinclair, Judi Dench",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"2006-11-17",
      "description":"This is the 21st movie of 007 films serie. In his first mission, James Bond must stop Le Chiffre, a banker to the world's terrorist organizations, from winning a high-stakes poker tournament at Casino Royale in Montenegro.",
      "rating":"PG-13",
      "studio":"MGM",
      "director":"Martin Campbell",
      "producers":"",
      "screenwriters":"Neal Purvis, Robert Wade",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Casino Royale/007_ Casino Royale.m4v"
    },
    {
      "id": "4",
      "name":"007: Diamonds Are Forever",
      "filename":"007_ Diamonds Are Forever.m4v",
      "artwork":"../img/artwork/00004/007_%20Diamonds%20Are%20Forever.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Sean Connery, Jill St. John, Charles Gray, Lana Wood, Jimmy Dean, Bruce Cabot, Putter Smith, Bruce Glover, Norman Burton, Joseph Fürst, Bernard Lee, Desmond Llewelyn, Lois Maxwell, Marc Lawrence, Laurence Naismith",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Science Fiction, Foreign",
      "release Date":"1971-12-17",
      "description":"Diamonds are stolen only to be sold again in the international market. James Bond infiltrates a smuggling mission to find out who’s guilty. The mission takes him to Las Vegas where Bond meets his archenemy Blofeld. The seventh film from the Legendary James Bond series starring Sean Connery as a British super agent.",
      "rating":"PG",
      "studio":"MGM, Eon Productions",
      "director":"Guy Hamilton",
      "producers":"Albert R. Broccoli, Harry Saltzman, Stanley Sopel",
      "screenwriters":"Ian Fleming, Richard Maibaum, Tom Mankiewicz",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Diamonds Are Forever/007_ Diamonds Are Forever.m4v"
    },
    {
      "id": "5",
      "name":"007: Die Another Day",
      "filename":"007_ Die Another Day.m4v",
      "artwork":"../img/artwork/00005/007_%20Die%20Another%20Day.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Halle Berry, Toby Stephens, Rosamund Pike, Rick Yune, John Cleese, Lawrence Makoare, Michael Madsen, Will Yun Lee, Kenneth Tsang Kong, Judi Dench, Emilio Echevarría, Mikhail Gorevoy, Colin Salmon, Samantha Bond, Madonna, Pierce Brosnan",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"2002-11-22",
      "description":"This is the 20th movie of 007 films serie. The ever-daring James Bond taking on a North Korean leader who undergoes DNA replacement procedures that allow him to assume different identities. American agent Jinx Johnson assists Bond in thwarting the villain's plans to exploit a satellite that is powered by solar energy.",
      "rating":"PG-13",
      "studio":"MGM, Eon Productions, United Artists",
      "director":"Lee Tamahori",
      "producers":"",
      "screenwriters":"Ian Fleming, Neal Purvis, Ian Fleming",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Die Another Day/007_ Die Another Day.m4v"
    },
    {
      "id": "6",
      "name":"007: Dr. No",
      "filename":"007_ Dr. No.m4v",
      "artwork":"../img/artwork/00006/007_%20Dr.%20No.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Sean Connery, Ursula Andress, Joseph Wiseman, Jack Lord, Bernard Lee, Anthony Dawson, Zena Marshall, John Kitzmiller, Eunice Gayson, Lois Maxwell, Peter Burton, Louis Blaazer",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1963-05-08",
      "description":"This is the 1st movie of 007 films serie. When Strangways, the British SIS Station Chief in Jamaica goes missing, MI6 send James Bond - Agent 007 to investigate. His investigation leads him to the mysterious Crab Key; the secret base of Dr No who he suspects is trying to sabotage the American space program using a radio beam. With the assistance of local fisherman Quarrel, who had been helping Strangways, Bond sneaks onto Crab Key where he meets the beautiful Honey Ryder. Can the three of them defeat an army of henchmen and a 'fire breathing dragon' in order to stop Dr No, save the space program and get revenge for Strangways? Dr. No is the first film of legendary James Bond series starring Sean Connery in the role of Fleming's British super agent.",
      "rating":"PG",
      "studio":"United Artists, Eon Productions",
      "director":"Terence Young",
      "producers":"Albert R. Broccoli, Harry Saltzman",
      "screenwriters":"Ian Fleming, Richard Maibaum, Johanna Harwood, Berkely Mather",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Dr. No/007_ Dr. No.m4v"
    },
    {
      "id": "7",
      "name":"007: For Your Eyes Only",
      "filename":"007_ For Your Eyes Only.m4v",
      "artwork":"../img/artwork/00007/007_%20For%20Your%20Eyes%20Only.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Roger Moore, Carole Bouquet, Topol, Lynn-Holly Johnson, Julian Glover, Cassandra Harris, Jill Bennett, Michael Gothard, John Wyman, Jack Hedley, Lois Maxwell, Desmond Llewelyn, Geoffrey Keen, Walter Gotell",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1981-06-24",
      "description":"This is the 12th movie of 007 films serie. A British spy ship has sunk and on board was a hi-tech encryption device. James Bond is sent to find the device that holds British launching instructions before the enemy Soviets get to it first. The twelfth film from the Legendary James Bond series starring Roger Moore as a British super agent.",
      "rating":"PG",
      "studio":"United Artists",
      "director":"John Glen",
      "producers":"Albert R. Broccoli, Tom Pevsner, Michael J. Wilson, Debbie McWilliams, Maude Spector",
      "screenwriters":"Richard Maibaum, Michael J. Wilson",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ For Your Eyes Only/007_ For Your Eyes Only.m4v"
    },
    {
      "id": "8",
      "name":"007: From Russia With Love",
      "filename":"007_ From Russia With Love.m4v",
      "artwork":"../img/artwork/00008/007_%20From%20Russia%20With%20Love.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Sean Connery, Daniela Bianchi, Lotte Lenya, Robert Shaw, Bernard Lee, Eunice Gayson, Walter Gotell, Francis De Wolff, George Pastell, Nadja Regin, Lois Maxwell, Aliza Gur, Desmond Llewelyn, Pedro Armendáriz, Vladek Sheybal",
      "main Genre":"Action & Adventure",
      "genres":"Action, Thriller, Foreign",
      "release Date":"1964-04-08",
      "description":"This is the 2nd movie of 007 films serie. Bond is back and on the loose in exotic Istanbul looking for a super-secret coding machine. He's involved with a beautiful Russian spy and has the SPECTRE organization after him, including villainess Rosa Klebb (she of the killer shoe). Lots of exciting escapes but not an overreliance on the gadgetry of the later films. The second Bond feature, thought by many to be the best.",
      "rating":"PG",
      "studio":"United Artists, Eon Productions",
      "director":"Terence Young",
      "producers":"Albert R. Broccoli, Harry Saltzman, Weston Drury Jr.",
      "screenwriters":"Ian Fleming, Richard Maibaum, Johanna Harwood",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ From Russia With Love/007_ From Russia With Love.m4v"
    },
    {
      "id": "9",
      "name":"007: GoldenEye",
      "filename":"007_ GoldenEye.m4v",
      "artwork":"../img/artwork/00009/007_%20GoldenEye.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Pierce Brosnan, Sean Bean, Izabella Scorupco, Famke Janssen, Joe Don Baker, Judi Dench, Gottfried John, Robbie Coltrane, Alan Cumming, Tchéky Karyo, Desmond Llewelyn, Samantha Bond, Michael Kitchen, Serena Gordon, Simon Kunz",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1995-11-17",
      "description":"This is the 17th movie of 007 films serie. James Bond must unmask the mysterious head of the Janus Syndicate and prevent his one time ally - Alec Trevelyan Agent 006 - from utilising the GoldenEye weapons system to inflict devastating revenge on Britain. --- The 17th film from the legendary James Bond series and the first starring Pierce Brosnan.",
      "rating":"PG-13",
      "studio":"United Artists, Eon Productions",
      "director":"Martin Campbell",
      "producers":"Barbara Broccoli, Anthony Waye, Tom Pevsner, Michael J. Wilson, Debbie McWilliams",
      "screenwriters":"Ian Fleming, Jeffrey Caine, Bruce Feirstein",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ GoldenEye/007_ GoldenEye.m4v"
    },
    {
      "id": "10",
      "name":"007: Goldfinger",
      "filename":"007_ Goldfinger.m4v",
      "artwork":"../img/artwork/00010/007_%20Goldfinger.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Sean Connery, Honor Blackman, Gert Fröbe, Shirley Eaton, Tania Mallet, Harold Sakata, Bernard Lee, Martin Benson, Cec Linder, Austin Willis, Lois Maxwell, Desmond Llewelyn, Burt Kwouk",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1964-12-25",
      "description":"Bond is in Miami on holiday when M tells him to observe Auric Goldfinger. Bond steals Goldfinger's girlfriend Jill Masterson, but after being knocked out, he awakes to find her dead and covered in gold paint. Upon returning to London, Bond is told to further investigate Goldfinger who is believed to be smuggling gold out of Britain, but warned he will be replaced if he turns the mission into a personal vendetta. After failing to befriend Goldfinger, Bond is caught spying and taken to America as a captive. Bond learns of Goldfinger's plan, codenamed Operation Grand Slam, which involves attacking Fort Know to increase his gold riches. Can 007 find a way to stop Goldfinger despite being held prisoner? This is the third film from the legendary James Bond series starring Sean Connery as the British super agent.",
      "rating":"PG",
      "studio":"United Artists, Eon Productions",
      "director":"Guy Hamilton",
      "producers":"Albert R. Broccoli, Harry Saltzman",
      "screenwriters":"Ian Fleming, Richard Maibaum, Paul Dehn",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Goldfinger/007_ Goldfinger.m4v"
    },
    {
      "id": "11",
      "name":"007: Licence to Kill",
      "filename":"007_ Licence to Kill.m4v",
      "artwork":"../img/artwork/00011/007_%20Licence%20to%20Kill.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Timothy Dalton, Carey Lowell, Robert Davi, Talisa Soto, Anthony Zerbe, Frank McRae, David Hedison, Wayne Newton, Benicio Del Toro, Anthony Starke, Everett McGill, Desmond Llewelyn, Pedro Armendáriz Jr., Robert Brown",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1989-07-14",
      "description":"James Bond and his American colleague Felix Leiter arrest the drug lord Sanchez who succeeds in escaping and takes revenge on Felix and his wife. Bond knows but just one thing: revenge. The 16th film from the Legendary James Bond series starring Timothy Dalton as a British super agent.",
      "rating":"PG-13",
      "studio":"United Artists",
      "director":"John Glen",
      "producers":"Albert R. Broccoli, Barbara Broccoli, Tom Pevsner, Michael J. Wilson, Janet Hirshenson, Jane Jenkins",
      "screenwriters":"Ian Fleming, Michael J. Wilson, Richard Maibaum",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Licence to Kill/007_ Licence to Kill.m4v"
    },
    {
      "id": "12",
      "name":"007: Live and Let Die",
      "filename":"007_ Live and Let Die.m4v",
      "artwork":"../img/artwork/00012/007_%20Live%20and%20Let%20Die.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Roger Moore, Yaphet Kotto, Jane Seymour, Clifton James, Julius Harris, Geoffrey Holder, David Hedison, Gloria Hendry, Bernard Lee, Lois Maxwell, Tommy Lane, Roy Stewart",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1973-07-05",
      "description":"This is the 8th movie of 007 films serie. James Bond must investigate a mysterious murder case of a British agent in New York. Soon he finds himself up against a big gangster boss named Mr. Big. This the eight film of the James Bond series and the first one to star Roger Moore as the British undercover agent 007.",
      "rating":"PG",
      "studio":"United Artists, Eon Productions",
      "director":"Guy Hamilton",
      "producers":"Albert R. Broccoli, Harry Saltzman, Weston Drury Jr.",
      "screenwriters":"Ian Fleming, Tom Mankiewicz",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Live and Let Die/007_ Live and Let Die.m4v"
    },
    {
      "id": "13",
      "name":"007: Moonraker",
      "filename":"007_ Moonraker.m4v",
      "artwork":"../img/artwork/00013/007_%20Moonraker.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Roger Moore, Lois Chiles, Michael Lonsdale, Corinne Cléry, Richard Kiel, Bernard Lee, Geoffrey Keen, Desmond Llewelyn, Lois Maxwell, Toshirô Suga, Emily Bolton, Blanche Ravalec",
      "main Genre":"Action & Adventure",
      "genres":"Action, Adventure, Foreign, Thriller",
      "release Date":"1979-06-26",
      "description":"This is the 11th movie of 007 films serie. During the transportation of a Space Shuttle a Boeing 747 crashes in the Atlantic Ocean yet when they go to look for the destroyed shuttle it is not there. James bond investigates the missing mission space shuttle and soon learns that the shuttles owner Hugo Drax wants to kill all of mankind. The showdown is about to take place in outer space. The eleventh film from the Legendary James Bond series",
      "rating":"PG",
      "studio":"United Artists, Eon Productions",
      "director":"Lewis Gilbert",
      "producers":"Albert R. Broccoli, William P. Cartlidge, Michael J. Wilson, Margot Capelier, Weston Drury Jr.",
      "screenwriters":"Christopher Wood",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Moonraker/007_ Moonraker.m4v"
    },
    {
      "id": "14",
      "name":"007: Octopussy",
      "filename":"007_ Octopussy.m4v",
      "artwork":"../img/artwork/00014/007_%20Octopussy.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Roger Moore, Maud Adams, Louis Jourdan, Kristina Wayborn, Kabir Bedi, Steven Berkoff, David Meyer, Tony Meyer, Desmond Llewelyn, Robert Brown, Lois Maxwell, Michaela Clavell, Walter Gotell, Vijay Amritraj, Albert Moses, Geoffrey Keen, Douglas Wilmer, Andy Bradford, Philip Voss, Bruce Boa, Richard LeParmentier, Paul Hardwick, Suzanne Jerome, Cherry Gillespie, Dermot Crowley, Peter Porteous, Eva Reuber-Staier, Jeremy Bulloch, Tina Hudson, William Derrick, Stuart Saunders, Patrick Barr",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1983-06-06",
      "description":"This is the 13th movie of 007 films serie. James Bond is sent to investigate after a fellow “00” agent is found dead with a priceless Farberge egg. James bond follows the mystery and uncovers a smuggling scandal and a Russian General who wants to provoke a new World War. The 13th film from the Legendary James Bond series starring Roger Moore as a British super agent.",
      "rating":"-- United States",
      "studio":"MGM, United Artists, Eon Productions",
      "director":"John Glen",
      "producers":"Albert R. Broccoli, Tom Pevsner, Michael J. Wilson, Debbie McWilliams",
      "screenwriters":"George MacDonald Fraser, Richard Maibaum, Michael J. Wilson, George MacDonald Fraser, Richard Maibaum, Michael J. Wilson",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Octopussy/007_ Octopussy.m4v"
    },
    {
      "id": "15",
      "name":"007: On Her Majesty's Secret Service",
      "filename":"007_ On Her Majesty's Secret Service.m4v",
      "artwork":"../img/artwork/00015/007_%20On%20Her%20Majesty's%20Secret%20Service.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"George Lazenby, Diana Rigg, Telly Savalas, Gabriele Ferzetti, Ilse Steppat, Angela Scoular, Lois Maxwell, George Baker, Bernard Lee, Bernard Horsfall, Desmond Llewelyn, Yuri Borionko, Catherine Schell",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1969-12-18",
      "description":"This is the 6th movie of 007 films serie. Bond tracks archnemesis Ernst Blofeld to a mountaintop retreat where he's training an army of beautiful but lethal women. Along the way, Bond falls for Italian contessa Tracy Draco -- and marries her in order to get closer to Blofeld. Meanwhile, he locates Blofeld in the Alps and embarks on a classic ski chase.",
      "rating":"PG",
      "studio":"MGM, United Artists",
      "director":"Peter R. Hunt",
      "producers":"Albert R. Broccoli, Harry Saltzman, Stanley Sopel",
      "screenwriters":"Richard Maibaum, Ian Fleming",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ On Her Majesty's Secret Service/007_ On Her Majesty's Secret Service.m4v"
    },
    {
      "id": "16",
      "name":"007: Quantum of Solace",
      "filename":"007_ Quantum of Solace.m4v",
      "artwork":"../img/artwork/00016/007_%20Quantum%20of%20Solace.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Daniel Craig, Olga Kurylenko, Mathieu Amalric, Judi Dench, Giancarlo Giannini, Gemma Arterton, Jeffrey Wright, David Harbour, Jesper Christensen, Anatole Taubman, Rory Kinnear, Tim Pigott-Smith, Joaquin Cosio, Jesus Ochoa, Glenn Foster, Paul Ritter, Simon Kassianides, Stana Katic, Lucrezia Lante della Rovere, Neil Jackson, Oona Chaplin, Laurence Richardson, Rachel McDowall, Gustavo Nanez, Mark Wakeling, Sarah Hadland, David Decio, Aaron King, Alexandra Prusa, Brandon Jovanovich, Alexandre Krawetz, Fernando Guillén Cuervo",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Crime, Foreign",
      "release Date":"2008-10-31",
      "description":"This is the 22nd movie of 007 films serie. Quantum of Solace continues the high octane adventures of James Bond in Casino Royale. Betrayed by Vesper, the woman he loved, 007 fights the urge to make his latest mission personal. Pursuing his determination to uncover the truth, Bond and M interrogate Mr White who reveals the organization which blackmailed Vesper is far more complex and dangerous than anyone had imagined.",
      "rating":"PG-13",
      "studio":"MGM",
      "director":"Marc Forster",
      "producers":"Michael G. Wilson, Barbara Broccoli, Callum McDougall, Anthony Waye, Gregg Wilson, Debbie McWilliams",
      "screenwriters":"Robert Wade, Neal Purvis, Paul Haggis",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Quantum of Solace/007_ Quantum of Solace.m4v"
    },
    {
      "id": "17",
      "name":"007: Skyfall",
      "filename":"007_ Skyfall.m4v",
      "artwork":"../img/artwork/00017/007_%20Skyfall.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Daniel Craig, Javier Bardem, Ralph Fiennes, Albert Finney, Naomie Harris, Tonia Sotiropoulou, Helen McCrory, Bérénice Marlohe, Ben Whishaw, Ola Rapace, Rory Kinnear, Judi Dench",
      "main Genre":"Action & Adventure",
      "genres":"Action, Adventure, Thriller",
      "release Date":"2012-11-09",
      "description":"When Bond's latest assignment goes gravely wrong and agents around the world are exposed, MI6 is attacked forcing M to relocate the agency. These events cause her authority and position to be challenged by Gareth Mallory (Ralph Fiennes), the new Chairman of the Intelligence and Security Committee. With MI6 now compromised from both inside and out, M is left with one ally she can trust: Bond. 007 takes to the shadows - aided only by field agent, Eve (Naomie Harris) - following a trail to the mysterious Silva (Javier Bardem), whose lethal and hidden motives have yet to reveal themselves.",
      "rating":"PG-13",
      "studio":"MGM, Columbia Pictures, Eon Productions, Danjaq",
      "director":"Sam Mendes",
      "producers":"Barbara Broccoli, Michael G. Wilson, Callum McDougall",
      "screenwriters":"John Logan, Paul Epworth, Robert Wade, Neal Purvis",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Skyfall/007_ Skyfall.m4v"
    },
    {
      "id": "18",
      "name":"007: The Living Daylights",
      "filename":"007_ The Living Daylights.m4v",
      "artwork":"../img/artwork/00018/007_%20The%20Living%20Daylights.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Timothy Dalton, Maryam d'Abo, Jeroen Krabbé, Joe Don Baker, John Rhys-Davies, Art Malik, Andreas Wisniewski, Thomas Wheatley, Desmond Llewelyn, Robert Brown, Geoffrey Keen, Walter Gotell, Caroline Bliss",
      "main Genre":"Action & Adventure",
      "genres":"Action, Adventure, Foreign, Thriller",
      "release Date":"1987-06-29",
      "description":"James Bond helps a Russian General escape into the west. He soon finds out that the KGB wants to kill him for helping the General. A little while later the General is kidnapped from the Secret Service leading 007 to be suspicious. The 15th film from the Legendary James Bond series starring Timothy Dalton as a British super agent.",
      "rating":"PG",
      "studio":"United Artists",
      "director":"John Glen",
      "producers":"Albert R. Broccoli, Barbara Broccoli, Tom Pevsner, Michael J. Wilson, Debbie McWilliams",
      "screenwriters":"Richard Maibaum, Michael J. Wilson",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ The Living Daylights/007_ The Living Daylights.m4v"
    },
    {
      "id": "19",
      "name":"007: The Man with the Golden Gun",
      "filename":"007_ The Man with the Golden Gun.m4v",
      "artwork":"../img/artwork/00019/007_%20The%20Man%20with%20the%20Golden%20Gun.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Roger Moore, Christopher Lee, Britt Ekland, Maud Adams, Hervé Villechaize, Clifton James, Richard Loo, Soon-Tek Oh, Marc Lawrence, Bernard Lee, Lois Maxwell, Desmond Llewelyn",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Comedy, Thriller, Foreign",
      "release Date":"1974-12-18",
      "description":"A golden bullet has 007 engraved on it as it smashes into the secret service headquarters. The bullet came from the professional killer Scaramanga who has yet to miss a target and James Bond begins a mission to try and stop him. The ninth film from the Legendary James Bond series starring Roger Moore as a British super agent.",
      "rating":"PG",
      "studio":"United Artists, Eon Productions",
      "director":"Guy Hamilton",
      "producers":"Albert R. Broccoli, Harry Saltzman, Charles Orme, Weston Drury Jr., Maude Spector",
      "screenwriters":"Ian Fleming, Richard Maibaum, Tom Mankiewicz",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ The Man with the Golden Gun/007_ The Man with the Golden Gun.m4v"
    },
    {
      "id": "20",
      "name":"007: The Spy Who Loved Me",
      "filename":"007_ The Spy Who Loved Me.m4v",
      "artwork":"../img/artwork/00020/007_%20The%20Spy%20Who%20Loved%20Me.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Roger Moore, Barbara Bach, Curd Jürgens, Richard Kiel, Caroline Munro, Walter Gotell, Geoffrey Keen, Bernard Lee, George Baker, Michael Billington, Olga Bisera, Desmond Llewelyn, Edward de Souza, Vernon Dobtcheff, Lois Maxwell, Sydney Tafler",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1977-07-07",
      "description":"This is the 10th movie of 007 films serie. Russian and American submarines with nuclear missels on board both vanish from sight without a trace. America and Russia both blame each other as James Bond tries to solve the riddle of the disappearing ships. But the KGB also has an agent on the case. The tenth film from the Legendary James Bond series starring Roger Moore as a British super agent.",
      "rating":"PG",
      "studio":"United Artists, Eon Productions",
      "director":"Lewis Gilbert",
      "producers":"Albert R. Broccoli, William P. Cartlidge, Weston Drury Jr., Maude Spector",
      "screenwriters":"Ian Fleming, Christopher Wood, Richard Maibaum",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ The Spy Who Loved Me/007_ The Spy Who Loved Me.m4v"
    },
    {
      "id": "21",
      "name":"007: The World Is Not Enough",
      "filename":"007_ The World Is Not Enough.m4v",
      "artwork":"../img/artwork/00021/007_%20The%20World%20Is%20Not%20Enough.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Pierce Brosnan, Sophie Marceau, Robert Carlyle, Denise Richards, Robbie Coltrane, Desmond Llewelyn, John Cleese, Maria Grazia Cucinotta, Samantha Bond, Michael Kitchen, Colin Salmon, David Calder, Serena Scott Thomas, Judi Dench",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1999-11-08",
      "description":"Greed, revenge, world dominance, high-tech terrorism -- it's all in a day's work for cunning MI6 agent James Bond, who's on a mission to protect beautiful oil heiress Elektra King from a notorious terrorist. In a race against time that culminates in a dramatic submarine showdown, Bond works to defuse the international power struggle that has the world's oil supply hanging in the balance.",
      "rating":"PG-13",
      "studio":"United Artists",
      "director":"Michael Apted",
      "producers":"",
      "screenwriters":"Neal Purvis, Robert Wade",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ The World Is Not Enough/007_ The World Is Not Enough.m4v"
    },
    {
      "id": "22",
      "name":"007: Thunderball",
      "filename":"007_ Thunderball.m4v",
      "artwork":"../img/artwork/00022/007_%20Thunderball.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Sean Connery, Claudine Auger, Adolfo Celi, Luciana Paluzzi, Rik Van Nutter, Guy Doleman, Molly Peters, Martine Beswick, Bernard Lee, Desmond Llewelyn, Lois Maxwell, Roland Culver, André Maranne",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1965-12-29",
      "description":"This is the 4th movie of 007 films serie. A criminal organization has obtained two nuclear bombs and are asking for a 100 million pound ransom in the form of diamonds in seven days or they will use the weapons. The secret service sends James Bond to the Bahamas to once again save the world.",
      "rating":"PG",
      "studio":"United Artists, Eon Productions",
      "director":"Terence Young",
      "producers":"Kevin McClory, Albert R. Broccoli, Harry Saltzman",
      "screenwriters":"Ian Fleming, Richard Maibaum, John Hopkins, Jack Whittingham",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Thunderball/007_ Thunderball.m4v"
    },
    {
      "id": "23",
      "name":"007: Tomorrow Never Dies",
      "filename":"007_ Tomorrow Never Dies.m4v",
      "artwork":"../img/artwork/00023/007_%20Tomorrow%20Never%20Dies.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Pierce Brosnan, Jonathan Pryce, Michelle Yeoh, Teri Hatcher, Ricky Jay, Götz Otto, Joe Don Baker, Vincent Schiavelli, Judi Dench, Desmond Llewelyn, Samantha Bond, Colin Salmon, Geoffrey Palmer, Julian Fellowes, Terence Rigby",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Action, Thriller, Foreign",
      "release Date":"1997-12-12",
      "description":"This is the 18th movie of 007 films serie. A deranged media mogul is staging international incidents to pit the world's superpowers against each other. Now 007 must take on this evil mastermind in an adrenaline-charged battle to end his reign of terror and prevent global pandemonium. --- The 18th film from the legendary James Bond series, starring Pierce Brosnan.",
      "rating":"PG-13",
      "studio":"United Artists",
      "director":"Roger Spottiswoode",
      "producers":"Debbie McWilliams, Barbara Broccoli, Michael J. Wilson, Anthony Waye",
      "screenwriters":"Bruce Feirstein, Ian Fleming",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ Tomorrow Never Dies/007_ Tomorrow Never Dies.m4v"
    },
    {
      "id": "24",
      "name":"007: You Only Live Twice",
      "filename":"007_ You Only Live Twice.m4v",
      "artwork":"../img/artwork/00024/007_%20You%20Only%20Live%20Twice.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Sean Connery, Akiko Wakabayashi, Karin Dor, Mie Hama, Tetsurô Tanba, Teru Shimada, Donald Pleasence, Bernard Lee, Lois Maxwell, Desmond Llewelyn, Charles Gray, Tsai Chin, Burt Kwouk",
      "main Genre":"Action & Adventure",
      "genres":"Action, Thriller, Foreign",
      "release Date":"1967-06-12",
      "description":"This is the 5th movie of 007 films serie. A mysterious space craft kidnaps a Russian and American space capsule and brings the world on the verge of another World War. James Bond investigates the case in Japan and meets with his archenemy Blofeld. The fifth film from the legendary James Bond series starring Sean Connery as the British super agent.",
      "rating":"PG",
      "studio":"Eon Productions, Danjaq",
      "director":"Lewis Gilbert",
      "producers":"Albert R. Broccoli, Harry Saltzman",
      "screenwriters":"Ian Fleming, Roald Dahl",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/007_ You Only Live Twice/007_ You Only Live Twice.m4v"
    },
    {
      "id": "25",
      "name":"10,000 BC",
      "filename":"10,000 BC.m4v",
      "artwork":"../img/artwork/00025/10,000%20BC.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Camilla Belle, Steven Strait, Cliff Curtis, Nathanael Baring, Mo Zinal, Affif Ben Badra, Mona Hammond, Marco Khan, Reece Ritchie, Joel Fry",
      "main Genre":"Action & Adventure",
      "genres":"Adventure, Drama",
      "release Date":"2008-03-06",
      "description":"A prehistoric epic that follows a young mammoth hunter's journey through uncharted territory to secure the future of his tribe.",
      "rating":"PG-13",
      "studio":"Centropolis Entertainment, Legendary Pictures",
      "director":"Roland Emmerich",
      "producers":"Roland Emmerich, Mark Gordon, Michael Wimer, Harald Kloser, Sarah Bradshaw, Tom Karnowski, Thomas Tull, William Fay",
      "screenwriters":"Harald Kloser, Roland Emmerich",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/10,000 BC/10,000 BC.m4v"
    },
    {
      "id": "26",
      "name":"12 Years a Slave",
      "filename":"12 Years a Slave (1080p HD).m4v",
      "artwork":"../img/artwork/00026/12%20Years%20a%20Slave%20(1080p%20HD).art[0].jpg",
      "hd":"1",
      "m4v":"1",
      "backup":"0",
      "artist":"Steve McQueen",
      "main Genre":"Drama",
      "genres":"Drama, History",
      "release Date":"2013-10-18",
      "description":"In the pre-Civil War United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery. Facing cruelty as well as unexpected kindnesses Solomon struggles not only to stay alive, but to retain his dignity. In the twelfth year of his unforgettable odyssey, Solomon’s chance meeting with a Canadian abolitionist will forever alter his life.",
      "rating":"R",
      "studio":"New Regency Pictures, Plan B Entertainment, River Road Entertainment, Summit Entertainment",
      "director":"Steve McQueen",
      "producers":"Dede Gardner, Jeremy Kleiner, Brad Pitt, Anthony Katagas, Arnon Milchan, Bill Pohlad, Steve McQueen",
      "screenwriters":"John Ridley, Solomon Northup",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/12 Years a Slave/12 Years a Slave (1080p HD).m4v"
    },
    {
      "id": "27",
      "name":"127 Hours",
      "filename":"127 Hours.m4v",
      "artwork":"../img/artwork/00027/127%20Hours.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"James Franco, Kate Mara, Amber Tamblyn, Sean Bott, Koleman Stinger, Treat Williams, John Lawrence, Kate Burton, Bailee Michelle Johnson, Rebecca C. Olson, Parker Hadley, Fenton Quinn, Lizzy Caplan, Clémence Poésy",
      "main Genre":"Drama",
      "genres":"Action, Adventure, Drama, Suspense, Thriller",
      "release Date":"2010-11-05",
      "description":"127 Hours is the true story of mountain climber Aron Ralston's (James Franco) remarkable adventure to save himself after a fallen boulder crashes on his arm and traps him in an isolated canyon in Utah. Over the next five days Ralston examines his life and survives the elements to finally discover he has the courage and the wherewithal to extricate himself by any means necessary, scale a 65 foot wall and hike over eight miles before he is finally rescued. Throughout his journey, Ralston recalls friends, lovers (Clemence Poesy), family, and the two hikers (Amber Tamblyn and Kate Mara) he met before his accident. Will they be the last two people he ever had the chance to meet?",
      "rating":"R",
      "studio":"James Franco, Kate Mara, Amber Tamblyn, Sean Bott, Koleman Stinger, Treat Williams, John Lawrence, Kate Burton, Bailee Michelle Johnson, Rebecca C. Olson, Parker Hadley, Fenton Quinn, Lizzy Caplan, Clémence Poésy",
      "director":"Danny Boyle",
      "producers":"",
      "screenwriters":"Simon Beaufoy, Danny Boyle",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/127 Hours/127 Hours.m4v"
    },
    {
      "id": "28",
      "name":"13 Assassins",
      "filename":"13 Assassins.m4v",
      "artwork":"../img/artwork/00028/13%20Assassins.art[0].jpg",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Takashi Miike",
      "main Genre":"Action & Adventure",
      "genres":"",
      "release Date":"2011-07-05T07:00:00Z",
      "description":"Cult director Takashi Miike (Ichi the Killer, Audition) delivers a bravado period action film set at the end of Japan’s feudal era. 13 Assassins - a “masterful exercise in cinematic butchery” (New York Post) - is centered around a group of elite samurai who are secretly enlisted to bring down a sadistic lord to prevent him from ascending to the throne and plunging the country into a war torn future.",
      "rating":"R",
      "studio":"Magnet",
      "director":"Takashi Miike",
      "producers":"Minami Ichikawa, Tôichirô Shiraishi, Michihiko Yanagisawa",
      "screenwriters":"Kaneo Ikegami, Daisuke Tengan",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/13 Assassins/13 Assassins.m4v"
    },
    {
      "id": "29",
      "name":"13",
      "filename":"13.m4v",
      "artwork":"../img/artwork/00029/13.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Jason Statham, Alexander Skarsgård, Gaby Hoffmann, Emmanuelle Chriqui, Mickey Rourke, David Zayas, Ray Winstone, Michael Shannon, Sam Riley, 50 Cent",
      "main Genre":"Thriller",
      "genres":"Drama, Thriller",
      "release Date":"2010-03-13",
      "description":"A naive young man assumes a dead man's identity and finds himself embroiled in an underground world of power, violence, and chance where men gamble behind closed doors on the lives of other men.",
      "rating":"R",
      "studio":"Jason Statham, Alexander Skarsgård, Gaby Hoffmann, Emmanuelle Chriqui, Mickey Rourke, David Zayas, Ray Winstone, Michael Shannon, Sam Riley, 50 Cent",
      "director":"Géla Babluani",
      "producers":"",
      "screenwriters":"Géla Babluani",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/13/13.m4v"
    },
    {
      "id": "30",
      "name":"1408",
      "filename":"1408.m4v",
      "artwork":"../img/artwork/00030/1408.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"John Cusack, Samuel L. Jackson, Mary McCormack, Jasmine Jessica Anthony, Tony Shalhoub, Alexandra Silber, Emily Harvey, Noah Lee Margetts, William Armstrong, Paul Birchard",
      "main Genre":"Horror",
      "genres":"Horror, Thriller",
      "release Date":"2007-06-12",
      "description":"The cynical and skeptical writer Mike Enslin writes books evaluating supernatural phenomena in hotels, graveyards and other haunted places, usually debunking the mystery. While writing his last book, he travels from Los Angeles to New York to spend one night in the evil room 1408 of the Dolphin Hotel, which is permanently unavailable for guests. The reluctant manager Mr. Gerald Olin objects to his request and offers an upgrade, expensive booze and finally the reports relating the death of more than fifty guests along decades in the cursed room. However, Mike threatens Mr. Oiln, promising to sue the hotel, and finally checks in the room. Along the night, he finds that guests of room 1408 can check out when they like, but they can never leave the room alive.",
      "rating":"R",
      "studio":"John Cusack, Samuel L. Jackson, Mary McCormack, Jasmine Jessica Anthony, Tony Shalhoub, Alexandra Silber, Emily Harvey, Noah Lee Margetts, William Armstrong, Paul Birchard",
      "director":"Mikael Håfström",
      "producers":"Lorenzo di Bonaventura, Jake Myers, Bob Weinstein, Harvey Weinstein",
      "screenwriters":"Scott Alexander, Larry Karaszewski, Stephen King, Matt Greenberg",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/1408/1408.m4v"
    },
    {
      "id": "31",
      "name":"2 Fast 2 Furious",
      "filename":"2 Fast 2 Furious (1080p HD).m4v",
      "artwork":"../img/artwork/00031/2%20Fast%202%20Furious%20(1080p%20HD).art[0].png",
      "hd":"1",
      "m4v":"1",
      "backup":"1",
      "artist":"Paul Walker, Tyrese Gibson, Eva Mendes, Cole Hauser, Ludacris, Thom Barry, James Remar, Devon Aoki, Amaury Nolasco, Michael Ealy, Jin Auyeung, Edward Finlay, Mark Boone Junior, Mo Gallini",
      "main Genre":"Action & Adventure",
      "genres":"Action, Adventure, Crime, Thriller",
      "release Date":"2003-06-02",
      "description":"It's a major double-cross when former police officer Brian O'Conner teams up with his ex-con buddy Roman Pearce to transport a shipment of 'dirty' money for shady Miami-based import-export dealer Carter Verone. But the guys are actually working with undercover agent Monica Fuentes to bring Verone down.",
      "rating":"PG-13",
      "studio":"Universal Pictures, Original Film, Mikona Productions GmbH & Co. KG",
      "director":"John Singleton",
      "producers":"Lee R. Mayes, Neal H. Moritz, Michael Fottrell",
      "screenwriters":"Derek Haas, Michael Brandt, Gary Scott Thompson, Gary Scott Thompson, Derek Haas, Michael Brandt",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/2 Fast 2 Furious/2 Fast 2 Furious (1080p HD).m4v"
    },
    {
      "id": "32",
      "name":"2 Guns",
      "filename":"2 Guns (1080p HD).m4v",
      "artwork":"../img/artwork/00032/2%20Guns%20(1080p%20HD).art[0].jpg",
      "hd":"1",
      "m4v":"1",
      "backup":"0",
      "artist":"Baltasar Kormákur",
      "main Genre":"Action & Adventure",
      "genres":"Action, Comedy, Crime, Drama, Thriller",
      "release Date":"2013-08-02",
      "description":"A DEA agent and an undercover Naval Intelligence officer who have been tasked with investigating one another find they have been set up by the mob -- the very organization the two men believe they have been stealing money from.",
      "rating":"R",
      "studio":"Universal Studios, Emmett/Furla Films, Envision Entertainment Corporation, Marc Platt Productions",
      "director":"Baltasar Kormákur",
      "producers":"Andrew Cosby, Randall Emmett, George Furla, Norton Herrick, Ross Richie, Adam Siegel, Marc Platt",
      "screenwriters":"Blake Masters, Steven Grant",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/2 Guns/2 Guns (1080p HD).m4v"
    },
    {
      "id": "33",
      "name":"2012",
      "filename":"2012.m4v",
      "artwork":"../img/artwork/00033/2012.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"John Cusack, Amanda Peet, Chiwetel Ejiofor, Danny Glover, Thandie Newton, Woody Harrelson, Liam James, Morgan Lily, Thomas McCarthy, Oliver Platt, Zlatko Buric, Beatrice Rosen, Chin Han, Osric Chau, Lisa Lu, John Billingsley, Johann Urb, George Segal, Blu Mankuma, Jimi Mistry, Agam Darshi, Stephen McHattie, Ryan McDonald",
      "main Genre":"Action & Adventure",
      "genres":"Action, Disaster, Thriller",
      "release Date":"2009-11-13",
      "description":"Dr. Adrian Helmsley, part of a worldwide geophysical team investigating the effect on the earth of radiation from unprecedented solar storms, learns that the earth's core is heating up. He warns U.S. President Thomas Wilson that the crust of the earth is becoming unstable and that without proper preparations for saving a fraction of the world's population, the entire race is doomed. Meanwhile, writer Jackson Curtis stumbles on the same information. While the world's leaders race to build 'arks' to escape the impending cataclysm, Curtis struggles to find a way to save his family. Meanwhile, volcanic eruptions and earthquakes of unprecedented strength wreak havoc around the world.",
      "rating":"PG-13",
      "studio":"Centropolis Entertainment, Sony Pictures",
      "director":"Roland Emmerich",
      "producers":"",
      "screenwriters":"Roland Emmerich, Harald Kloser",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/2012/2012.m4v"
    },
    {
      "id": "34",
      "name":"21 & Over",
      "filename":"21 & Over (1080p HD).m4v",
      "artwork":"../img/artwork/00034/21%20&%20Over%20(1080p%20HD).art[0].jpg",
      "hd":"1",
      "m4v":"1",
      "backup":"0",
      "artist":"Scott Moore, Jon Lucas",
      "main Genre":"Comedy",
      "genres":"Comedy",
      "release Date":"2013-03-01",
      "description":"Brilliant student Jeff Chang has the most important interview of his life tomorrow. But today is still his birthday, what starts off as a casual celebration with friends evolves into a night of debauchery that risks to derail his life plan.",
      "rating":"R",
      "studio":"Mandeville Films, Relativity Media",
      "director":"Scott Moore, Jon Lucas",
      "producers":"Hugo Shong, Andy Yan",
      "screenwriters":"Jon Lucas",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/21 & Over/21 & Over (1080p HD).m4v"
    },
    {
      "id": "35",
      "name":"21 Jump Street",
      "filename":"21 Jump Street.m4v",
      "artwork":"../img/artwork/00035/21%20Jump%20Street.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Channing Tatum, Jonah Hill, Brie Larson, Ellie Kemper, Ice Cube, Dave Franco, Nick Offerman, Lindsey Broad, Rob Riggle, Johnny Depp",
      "main Genre":"Comedy",
      "genres":"Action, Comedy, Family",
      "release Date":"2012-03-16",
      "description":"An undercover police unit consisting of young looking officers infiltrate high schools to control youth crime.",
      "rating":"R",
      "studio":"Columbia Pictures, Metro-Goldwyn-Mayer Pictures, Relativity Media, Original Film, Stephen J. Cannell Productions, Cannell Studios",
      "director":"Phil Lord, Chris Miller",
      "producers":"",
      "screenwriters":"Michael Bacall, Michael Bacall, Jonah Hill",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/21 Jump Street/21 Jump Street.m4v"
    },
    {
      "id": "36",
      "name":"21",
      "filename":"21.m4v",
      "artwork":"../img/artwork/00036/21.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Jim Sturgess, Kevin Spacey, Kate Bosworth, Laurence Fishburne, Aaron Yoo, Liza Lapira, Jacob Pitts, Jack McGee, Josh Gad, Sam Golzari, Ben Campbell",
      "main Genre":"Drama",
      "genres":"Crime, Drama",
      "release Date":"2008-03-07",
      "description":"Ben Campbell is a young, highly intelligent, student at M.I.T. in Boston who strives to succeed. Wanting a scholarship to transfer to Harvard School of Medicine with the desire to become a doctor, Ben learns that he cannot afford the $300,000 for the four to five years of schooling as he comes from a poor, working-class background. But one evening, Ben is introduced by his unorthodox math professor Micky Rosa into a small but secretive club of five. Students Jill, Choi, Kianna, and Fisher, who are being trained by Professor Rosa of the skill of card counting at blackjack.",
      "rating":"PG-13",
      "studio":"Columbia Pictures",
      "director":"Robert Luketic",
      "producers":"Dana Brunetti, Michael De Luca, William S. Beasley, Brett Ratner, Ryan Kavanaugh, Brett Ratner, Francine Maisler",
      "screenwriters":"Peter Steinfeld, Allan Loeb, Ben Mezrich",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/21/21.m4v"
    },
    {
      "id": "37",
      "name":"27 Dresses",
      "filename":"27 Dresses.m4v",
      "artwork":"../img/artwork/00037/27%20Dresses.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Katherine Heigl, James Marsden, Malin Åkerman, Judy Greer, Edward Burns, Brian Kerwin, Michael Ziegfeld, Melora Hardin, David Castro",
      "main Genre":"Comedy & Romance",
      "genres":"Comedy, Romance",
      "release Date":"2008-01-10",
      "description":"After serving as a bridesmaid 27 times, a young woman wrestles with the idea of standing by her sister's side as her sibling marries the man she's secretly in love with.",
      "rating":"PG-13",
      "studio":"Fox 2000 Pictures, Spyglass Entertainment, Birnbaum/Barber Production",
      "director":"Anne Fletcher",
      "producers":"Robert F. Newmyer, Michael Mayer, Roger Birnbaum, Gary Barber, Jonathan Glickman, Becki Cross Trujillo, Erin Stam",
      "screenwriters":"Aline Brosh McKenna",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/27 Dresses/27 Dresses.m4v"
    },
    {
      "id": "38",
      "name":"28 Weeks Later",
      "filename":"28 Weeks Later.m4v",
      "artwork":"../img/artwork/00038/28%20Weeks%20Later.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Jeremy Renner, Rose Byrne, Idris Elba, Catherine McCormack, Harold Perrineau, Imogen Poots, Mackintosh Muggleton, Shahid Ahmed, Robert Carlyle",
      "main Genre":"Horror",
      "genres":"Action, Adventure, Foreign, Horror, Science Fiction, Thriller",
      "release Date":"2007-05-11",
      "description":"In this chilling sequel to 28 Days Later, the inhabitants of the British Isles appear to have lost their battle against the onslaught of disease, as the deadly rage virus has killed every citizen there. Six months later, a group of Americans dare to set foot on the isles, convinced the danger has come and gone. But it soon becomes all too clear that the scourge continues to live, waiting to pounce on its next victims.",
      "rating":"R",
      "studio":"Figment Films, Sogecine, Koan Films",
      "director":"Juan Carlos Fresnadillo",
      "producers":"Danny Boyle, Alex Garland, Bernard Bellew, Allon Reich, Andrew Macdonald, Enrique López Lavigne",
      "screenwriters":"Rowan Joffe, Juan Carlos Fresnadillo, Jesús Olmo",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/28 Weeks Later/28 Weeks Later.m4v"
    },
    {
      "id": "39",
      "name":"3 Musketeers",
      "filename":"3 Musketeers.m4v",
      "artwork":"../img/artwork/00039/3%20Musketeers.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"David Chokachi, Heather Hemmens, Xin Sarith Wuku, Michele Boyd, Kane Hodder, Darren Anthony Thomas, Mam Smith, Carl Ciarfalio, Timothy Ingles, Steven Williams, Gerald Webb, Edward DeRuiter, Lauren Sparrow, Cham Nou, Malay Choeung Kim",
      "main Genre":"Action & Adventure",
      "genres":"Action, Adventure, Thriller",
      "release Date":"2011-10-25",
      "description":"Alexandra D'Artagnan, junior member of NSA uncovers a conspiracy that the goal is to assassinate the American president. Alexandra has secured the support of three famous and notorious international spies in order to stop the assassination.",
      "rating":"-- United States",
      "studio":"",
      "director":"Cole S. McKay",
      "producers":"",
      "screenwriters":"Edward DeRuiter",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/3 Musketeers/3 Musketeers.m4v"
    },
    {
      "id": "40",
      "name":"30 Minutes or Less",
      "filename":"30 Minutes or Less.m4v",
      "artwork":"../img/artwork/00040/30%20Minutes%20or%20Less.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Jesse Eisenberg, Danny McBride, Aziz Ansari, Bianca Kajlich, Nick Swardson, Michael Peña, Fred Ward, Dilshad Vadsaria",
      "main Genre":"Comedy",
      "genres":"Action, Comedy, Adventure",
      "release Date":"2011-08-12",
      "description":"Two fledgling criminals kidnap a pizza delivery guy, strap a bomb to his chest, and advise him that he has mere hours to rob a bank or else...",
      "rating":"R",
      "studio":"Jesse Eisenberg, Danny McBride, Aziz Ansari, Bianca Kajlich, Nick Swardson, Michael Peña, Fred Ward, Dilshad Vadsaria",
      "director":"Ruben Fleischer",
      "producers":"",
      "screenwriters":"Michael Diliberti",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/30 Minutes or Less/30 Minutes or Less.m4v"
    },
    {
      "id": "41",
      "name":"300",
      "filename":"300.m4v",
      "artwork":"../img/artwork/00041/300.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Gerard Butler, Andrew Pleavin, Vincent Regan, Lena Headey, David Wenham",
      "main Genre":"Action & Adventure",
      "genres":"Action, Adventure, Fantasy, History, War",
      "release Date":"2006-12-09",
      "description":"Based on Frank Miller's graphic novel, '300' concerns the 480 B.C. Battle of Thermopylae, where the King of Sparta led his army against the advancing Persians; the battle is said to have inspired all of Greece to band together against the Persians, and helped usher in the world's first democracy.",
      "rating":"R",
      "studio":"Warner Bros. Pictures, Legendary Pictures, Virtual Studios, Hollywood Gang Productions, Atmosphere Entertainment MM",
      "director":"Zack Snyder",
      "producers":"Gianni Nunnari, Kristy Carlson, Carrie Hilton, Andrea Kenyon, Tamara Notcutt",
      "screenwriters":"Frank Miller, Zack Snyder, Kurt Johnstad",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/300/300.m4v"
    },
    {
      "id": "42",
      "name":"360",
      "filename":"360.m4v",
      "artwork":"../img/artwork/00042/360.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Rachel Weisz, Jude Law, Ben Foster, Anthony Hopkins, Moritz Bleibtreu, Jamel Debbouze, Mark Ivanir, Katrina Vasilieva, Peter Morgan, Tereza Srbova, Kelvin Wise, Gabriela Marcinkova, Vladimir Vdovichenkov, Riann Steele, Sydney Wade, Johannes Krisch, Lucia Siposová, Sean Power, Maria Flor, Shaun Lucas, Russell Balogh, Dinara Drukarova, Gerard Monaco, Alex Sanders",
      "main Genre":"Drama",
      "genres":"Drama, Romance",
      "release Date":"2011-08-11",
      "description":"Inspired by Arthur Schnitzler's classic La Ronde, screenwriter Peter Morgan and director Fernando Meirelles' 360 combines a modern and dynamic roundelay of stories into one, linking characters from different cities and countries in a vivid, suspenseful and deeply moving tale of love in the 21st century. Starting in Vienna, the film beautifully weaves through Paris, London, Bratislava, Rio, Denver and Phoenix into a single, mesmerizing narrative.",
      "rating":"R",
      "studio":"",
      "director":"Fernando Meirelles",
      "producers":"Andrew Eaton, Chris Hanley, Danny Krausz, David Linde, Emanuel Michael",
      "screenwriters":"Peter Morgan",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/360/360.m4v"
    },
    {
      "id": "43",
      "name":"42",
      "filename":"42.m4v",
      "artwork":"../img/artwork/00043/42.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Chadwick Boseman, T.R. Knight, Harrison Ford, Nicole Beharie, Christopher Meloni, Jon Bernthal, John C. McGinley, Ryan Merriman, Jud Tylor, Brett Cullen, Brad Beyer, Lucas Black",
      "main Genre":"Sports",
      "genres":"Drama, Sports",
      "release Date":"2013-04-12",
      "description":"'42' is the powerful story of Jackie Robinson, the legendary baseball player who broke Major League Baseball's color barrier when he joined the roster of the Brooklyn Dodgers. The film follows the innovative Dodger's general manager Branch Rickey, the MLB executive who first signed Robinson to the minors and then helped to bring him up to the show.",
      "rating":"PG-13",
      "studio":"Warner Bros.",
      "director":"Brian Helgeland",
      "producers":"Jason Clark, Dick Cook, Jon Jashni, Thomas Tull",
      "screenwriters":"Brian Helgeland",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/42/42.m4v"
    },
    {
      "id": "44",
      "name":"47 Ronin",
      "filename":"47 Ronin (1080p HD).m4v",
      "artwork":"../img/artwork/00044/47%20Ronin%20(1080p%20HD).art[0].jpg",
      "hd":"1",
      "m4v":"1",
      "backup":"0",
      "artist":"Carl Rinsch",
      "main Genre":"Action & Adventure",
      "genres":"Action, Adventure, Fantasy",
      "release Date":"2013-12-25",
      "description":"Based on the original 1941 movie from Japan, and from ancient Japan’s most enduring tale, the epic 3D fantasy-adventure 47 Ronin is born. Keanu Reeves leads the cast as Kai, an outcast who joins Oishi (Hiroyuki Sanada), the leader of the 47 outcast samurai. Together they seek vengeance upon the treacherous overlord who killed their master and banished their kind. To restore honor to their homeland, the warriors embark upon a quest that challenges them with a series of trials that would destroy ordinary warriors. 47 Ronin is helmed by visionary director Carl Erik Rinsch (The Gift). Inspired by styles as diverse as Miyazaki and Hokusai, Rinsch will bring to life the stunning landscapes and enormous battles that will display the timeless Ronin story to global audiences in a way that’s never been seen before.",
      "rating":"PG-13",
      "studio":"Universal Pictures, H2F Entertainment, Mid Atlantic Films, Moving Picture Company (MPC), Stuber Productions",
      "director":"Carl Rinsch",
      "producers":"Scott Stuber, Pamela Abdy, Eric McLeod",
      "screenwriters":"Chris Morgan, Hossein Amini",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/47 Ronin/47 Ronin (1080p HD).m4v"
    },
    {
      "id": "45",
      "name":"50/50",
      "filename":"50_50.m4v",
      "artwork":"../img/artwork/00045/50_50.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Joseph Gordon-Levitt, Seth Rogen, Anna Kendrick, Bryce Dallas Howard, Anjelica Huston, Serge Houde, Andrew Airlie, Matt Frewer, Philip Baker Hall",
      "main Genre":"Comedy",
      "genres":"Comedy, Drama",
      "release Date":"2011-09-30",
      "description":"Inspired by a true story, a comedy centered on a 27-year-old guy who learns of his cancer diagnosis, and his subsequent struggle to beat the disease.",
      "rating":"R",
      "studio":"Joseph Gordon-Levitt, Seth Rogen, Anna Kendrick, Bryce Dallas Howard, Anjelica Huston, Serge Houde, Andrew Airlie, Matt Frewer, Philip Baker Hall",
      "director":"Jonathan Levine",
      "producers":"",
      "screenwriters":"Will Reiser",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/50_50/50_50.m4v"
    },
    {
      "id": "46",
      "name":"6 Bullets",
      "filename":"6 Bullets.m4v",
      "artwork":"../img/artwork/00046/6%20Bullets.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Jean-Claude Van Damme, Kristopher Van Varenberg, Bianca Bree, Joe Flanigan, Anna-Louise Plowman, Terese Cilluffo, Louis Dempsey, Uriel Emil Pollack, Charlotte Beaumont, Jimmy Townsend",
      "main Genre":"Action & Adventure",
      "genres":"Action, Thriller",
      "release Date":"2012-09-11",
      "description":"An ex-mercenary known for finding missing children is hired by a mixed martial arts fighter whose daughter has been kidnapped.",
      "rating":"R",
      "studio":"Motion Picture Corporation of America (MPCA)",
      "director":"Ernie Barbarash",
      "producers":"",
      "screenwriters":"Chad Law, Evan Law",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/6 Bullets/6 Bullets.m4v"
    },
    {
      "id": "47",
      "name":"88 Minutes",
      "filename":"88 Minutes.m4v",
      "artwork":"../img/artwork/00047/88%20Minutes.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Al Pacino, Alicia Witt, Leelee Sobieski, Amy Brenneman, William Forsythe, Deborah Kara Unger, Benjamin McKenzie, Neal McDonough, Leah Cairns, Stephen Moyer, Christopher Redman, Brendan Fletcher",
      "main Genre":"Thriller",
      "genres":"Crime, Mystery, Suspense, Thriller",
      "release Date":"2007-03-02",
      "description":"'88 Minutes' focuses on a college professor (Pacino) who moonlights as a forensic psychiatrist for the FBI and receives a death threat claiming he has only 88 minutes to live.",
      "rating":"-- United States",
      "studio":"Millennium Films",
      "director":"Jon Avnet",
      "producers":"Gary Scott Thompson, Randall Emmett, Michael P. Flannigan, Avi Lerner, Maureen Webb, Richard Pagano, Jon Avnet, George Furla",
      "screenwriters":"Gary Scott Thompson",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/88 Minutes/88 Minutes.m4v"
    },
    {
      "id": "48",
      "name":"9",
      "filename":"9.m4v",
      "artwork":"../img/artwork/00048/9.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Elijah Wood, John C. Reilly, Jennifer Connelly, Christopher Plummer, Crispin Glover, Martin Landau, Fred Tatasciore",
      "main Genre":"Kids & Family",
      "genres":"Adventure, Animation, Drama, Action, Romance",
      "release Date":"2009-09-09",
      "description":"When 9 first comes to life, he finds himself in a post-apocalyptic world. All humans are gone, and it is only by chance that he discovers a small community of others like him taking refuge from fearsome machines that roam the earth intent on their extinction. Despite being the neophyte of the group, 9 convinces the others that hiding will do them no good.",
      "rating":"PG-13",
      "studio":"Focus Films, Relativity Media",
      "director":"Shane Acker",
      "producers":"Jim Lemley, Тимур Бекмамбетов, Tim Burton, Dana Ginsburg, Mary Clayton, Jinko Gotoh, Marci Levine, Mindy Marin",
      "screenwriters":"Pamela Pettler, Shane Acker",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/9/9.m4v"
    },
    {
      "id": "49",
      "name":"A Better Life",
      "filename":"A Better Life.m4v",
      "artwork":"../img/artwork/00049/A%20Better%20Life.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Demián Bichir, Nancy Lenehan, Tim Griffin, Olivia Presley",
      "main Genre":"Drama",
      "genres":"Drama",
      "release Date":"2011-06-24",
      "description":"A gardener in East L.A. struggles to keep his son away from gangs and immigration agents while traveling across town to perform landscaping work for the city's wealthy landowners.",
      "rating":"PG-13",
      "studio":"Demián Bichir, Nancy Lenehan, Tim Griffin, Olivia Presley",
      "director":"Chris Weitz",
      "producers":"",
      "screenwriters":"Eric Eason, Roger L. Simon",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/A Better Life/A Better Life.m4v"
    },
    {
      "id": "50",
      "name":"A Dangerous Man",
      "filename":"A Dangerous Man.m4v",
      "artwork":"../img/artwork/00050/A%20Dangerous%20Man.art[0].png",
      "hd":"0",
      "m4v":"1",
      "backup":"1",
      "artist":"Steven Seagal, Marlaina Mah, Vitaly Kravchenko",
      "main Genre":"Action & Adventure",
      "genres":"Action, Adventure, Thriller",
      "release Date":"2009-01-01",
      "description":"After serving 6 years for a crime he didn't commit, Shane Daniels is released from jail with an apology from the State of Arizona. Within hours of his freedom, he unluckily bears witness to a cop killing by Chinese mafia who have a kidnapped girl and a bag of drug money",
      "rating":"-- United States",
      "studio":"My Own Worst Enemy",
      "director":"Keoni Waxman",
      "producers":"",
      "screenwriters":"Keoni Waxman",
      "media Kind":"Movie",
      "path":"/Volumes/Media Center/Shared iTunes/iTunes Media/Movies/A Dangerous Man/A Dangerous Man.m4v"
    },
];
